#include <cstdio>
#include <string>
#include <iostream>
#include <vector>

using namespace std;

#define print(x) cout << x << endl
#define input(x) cin >> x

const string s = "KKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKsssssjjjjiKKKKKssssrjjjjeKKKKIssssjjjjjeKKKKssssrjjjjiKKKKIssssrjjjjeKKKKIssssjjjjiKKKKKssssrjjjjiKKKKIssssjjjjjeKKKKsssssjjjjiKKKKIssssrjjjjeKKKKIssssjje";
const string mp = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789<>";

vector<int> mm(256);
vector<int> res(123456);

int main() {
    for (int i = 0; i < 64; i++) {
        mm[mp[i]] = i;
    }

    int cur = 0;
    int ptr = 0;
    for (int i = 0; i < s.size(); i++) {
        int u = mm[s[i]];
        for (int j = 5; j >= 0; j--) {
            int v = ((u & (1 << j))? 1: 0) + 3;

            for (int k = 0; k < v; k++) {
                res[ptr] = cur;
                ptr++;
            }
            cur += 1;
        }
    }

    int x;
    int case_ = 0;
    while (input(x)) {
        printf("Case #%d: %d\n", ++case_, res[x]);
    }

    return 0;
}
